name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install ruff pytest pytest-cov pytest-profiling

    - name: Lint with ruff
      run: |
        ruff check .
        ruff format --check .

    - name: Test, coverage, and profiling
      run: |
        pytest --cov=src --cov-report=xml --profile

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml

    - name: Upload profiling data
      uses: actions/upload-artifact@v3
      with:
        name: profiling-data
        path: prof
