name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip cache purge
          pip install -r requirements-dev.txt
      - name: Build docs
        run: mkdocs build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: site
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone https://github.com/${{ github.repository }}.git --branch gh-pages --single-branch gh-pages-deploy
          cp -r site/* gh-pages-deploy/
          cd gh-pages-deploy
          git add .
          git commit -m "docs: deploy to gh-pages"
          git push --force https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gh-pages
      
